name: Cleanup Images

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 1"

env:
  # TODO: REMOVEME: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: ice-launcher
          delete-untagged: true
          older-than: 3 months
